#!/bin/bash

cd ~
wget http://ellcc.org/releases/latest/ellcc-x86_64-linux-2017-08-23.bz2 -O ellcc.bz2
tar xfp ellcc.bz2
rm -rf ellcc.bz2
cd ellcc
./ellcc install
./ellcc install libraries

cd ~ 
wget https://raw.githubusercontent.com/tonikelope/megadown/master/helpers.py
chmod +x helpers.py
wget https://raw.githubusercontent.com/tonikelope/megadown/master/megadown
chmod +x megadown
sudo apt-get install -y pv
./megadown 'https://mega.nz/#!ZJQRkIrK!AQR0jZOyRP_8yy32OQ_fP9trqphsgOOh74jYLnuHMLQ'
unzip ecc-gdb7.zip
mv ecc-gdb7 ellcc/bin/ecc-gdb
rm -rf ecc-gdb7.zip helpers.py megadown
echo "export PATH=$PATH:~/ellcc/bin" >> ~/.bashrc
export PATH=$PATH:~/ellcc/bin
echo "alias mips-ecc=\"ecc -target mips32r2el\"" >> ~/.bashrc
sudo apt-get install qemu

