#!/bin/bash

cd ~
wget http://ellcc.org/releases/latest/ellcc-x86_64-linux-2017-08-23.bz2 -O ellcc.bz2
tar xfp ellcc.bz2
rm -rf ellcc.bz2
cd ellcc
./ellcc install
./ellcc install libraries

echo "export PATH=$PATH:~/ellcc/bin" >> ~/.bashrc
export PATH=$PATH:~/ellcc/bin
echo "alias mips-ecc=\"ecc -target mips32r2el-linux\"" >> ~/.bashrc
sudo apt install qemu gdb-multiarch
